### ISSUE TITLE
Question: on launch from closed enter empty document?

### ISSUE THREAD

**Issue by atomhax** [danielsaidi/DocumentKit#3]
There is a specific behavior a lot of Document based apps In UIKit adopt and I'm wondering if we could recreate it here as well. I'd be happy to work on it and open a PR if you think there is potential. 

Essentially when opening the app from a fresh launch instead of landing on the document picker we instead land on an empty "new" document. This allows the user to start editing almost immediately. My only issue with this approach is it is not very apple centric.

**Comment by danielsaidi** [comment]
Hi @atomhax 

I think that sounds like a great addition, but I'm not sure how that would be done with the standard document setup? Do you need to use a document reference for that first window?

If you want to create a PR for it, I'd love to have a look and add it to the library. We could perhaps aim for a modifier like the onboarding and splash modifiers?

**Comment by danielsaidi** [comment]
Hi @atomhax 

I'm closing this since iOS 18 changes the `DocumentGroup` quote dramatically, in ways that make me consider removing this SDK in a year or so, if we haven't found a reason for it to exist.
