### ISSUE TITLE
Issue with IOS 18

### ISSUE THREAD

**Issue by easiwriter** [danielsaidi/DocumentKit#5]
I've just tried the Demo on Xcode 16.0 beta 3. If you run it on an IOS 18 sim you get the (horrible) result below, which has screwed up the DocumentKit Toolbar. It's OK on an IOS 17 sim (with Xcode beta)

<img width="344" alt="Screenshot 2024-07-21 at 10 35 44" src="https://github.com/user-attachments/assets/8fbbcbc0-a336-4c5e-861e-9dd61f529700">

_Originally posted by @easiwriter in https://github.com/danielsaidi/DocumentKit/issues/4#issuecomment-2241546207_

**Comment by danielsaidi** [comment]
Thank you for sharing @easiwriter 🙏

**Comment by danielsaidi** [comment]
We can continue discussing this in #6 👍
